"""Scheduled GitHub Action scaffolding (`init --github-action`).

Renders ``.github/workflows/lineage-wiki-update.yml``: a daily run that
installs the tool, applies `lineage-wiki update` for one configured chain,
validates the catalog, and opens a pull request only when OKF content
actually changed (update runs are strict no-ops otherwise, so quiet days
produce no branch, no commit, and no PR).

Secrets are referenced through ``secrets.*`` expressions only — nothing
secret is rendered into the file, credentials are materialized into
``$RUNNER_TEMP`` (outside the repo checkout), and the PR step only stages
``okf/`` and ``.lineage-wiki/``. All secrets are optional except the
built-in ``GITHUB_TOKEN`` the PR step uses.
"""

from __future__ import annotations

WORKFLOW_REL_PATH = ".github/workflows/lineage-wiki-update.yml"

WORKFLOW_YAML = """\
# Generated by `lineage-wiki init --github-action`.
#
# Secrets (Settings -> Secrets and variables -> Actions), all optional:
#   OPENAI_API_KEY / ANTHROPIC_API_KEY  only needed if you add --use-llm below
#   GCP_SERVICE_ACCOUNT_JSON            service-account JSON for BigQuery
#                                       schema ingestion / verify-bq; without
#                                       it, `required: false` sources become
#                                       Known Gaps and the run still succeeds
# The PR step authenticates with the workflow's built-in GITHUB_TOKEN.
# Secret values never enter the repository: credentials are written to
# $RUNNER_TEMP and the PR only stages okf/ and .lineage-wiki/.
name: Lineage Wiki Update

on:
  schedule:
    - cron: "17 2 * * *"
  workflow_dispatch: {}

permissions:
  contents: write
  pull-requests: write

jobs:
  update:
    runs-on: ubuntu-latest
    env:
      # Optional model-provider keys, read at run time and never stored.
      # Change this if your generated manifest belongs to another chain config.
      LINEAGE_WIKI_CONFIG: chains/example.yml
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
      GCP_SA_JSON: ${{ secrets.GCP_SERVICE_ACCOUNT_JSON }}
    steps:
      - name: Check out the OKF repo
        uses: actions/checkout@v4

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install lineage-wiki
        # Adjust the spec if you install from a git URL instead of an index,
        # e.g. "lineage-wiki[bigquery] @ git+https://github.com/<org>/lineage-wiki".
        run: |
          python -m pip install --upgrade pip
          python -m pip install "lineage-wiki[bigquery]"

      - name: Configure BigQuery credentials (optional)
        if: env.GCP_SA_JSON != ''
        run: |
          printf '%s' "$GCP_SA_JSON" > "$RUNNER_TEMP/gcp-service-account.json"
          echo "GOOGLE_APPLICATION_CREDENTIALS=$RUNNER_TEMP/gcp-service-account.json" >> "$GITHUB_ENV"

      - name: Update OKF pages from configured sources
        run: |
          test -f "$LINEAGE_WIKI_CONFIG"
          echo "::group::lineage-wiki update --config $LINEAGE_WIKI_CONFIG"
          lineage-wiki update --config "$LINEAGE_WIKI_CONFIG"
          echo "::endgroup::"

      - name: Validate the knowledge graph
        run: lineage-wiki validate

      - name: Detect OKF content changes
        id: changes
        run: |
          if git status --porcelain okf .lineage-wiki | grep -q .; then
            echo "changed=true" >> "$GITHUB_OUTPUT"
          else
            echo "changed=false" >> "$GITHUB_OUTPUT"
          fi

      - name: Open a pull request with the updates
        if: steps.changes.outputs.changed == 'true'
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          add-paths: |
            okf/
            .lineage-wiki/
          branch: lineage-wiki/update
          commit-message: "lineage-wiki: scheduled OKF update"
          title: "Scheduled OKF update"
          body: |
            Automated `lineage-wiki update` run.

            - Source fingerprints changed since the last recorded run; only
              affected tool-owned pages were rewritten.
            - `lineage-wiki validate` passed on the updated tree.
            - Review the diff, then merge to accept the documentation update.
"""


def render_workflow() -> str:
    """The workflow file content — deterministic, no inputs."""
    return WORKFLOW_YAML
