"""Manifest reading/writing and fingerprint diffing under .lineage-wiki/."""

from __future__ import annotations

import hashlib
import os
import time
from contextlib import contextmanager
from dataclasses import dataclass, field
from collections.abc import Iterator
from pathlib import Path

import yaml
from pydantic import BaseModel, ConfigDict, Field, model_validator

from ..constants import MANIFEST_FILE


class ManifestLockError(RuntimeError):
    """Raised when the manifest lock cannot be acquired."""


class RepoFingerprint(BaseModel):
    model_config = ConfigDict(extra="ignore")

    ref: str | None = None
    git_head: str | None = None
    paths_hash: str | None = None


class SourceFingerprints(BaseModel):
    model_config = ConfigDict(extra="ignore")

    repos: dict[str, RepoFingerprint] = Field(default_factory=dict)
    bigquery: dict[str, str] = Field(default_factory=dict)
    raw_docs: dict[str, str] = Field(default_factory=dict)
    # Extensions beyond the spec example, needed for deterministic updates:
    # report-mapping and Slack-message fingerprints plus a hash of the
    # scaffold-relevant config.
    reports: dict[str, str] = Field(default_factory=dict)
    slack: dict[str, str] = Field(default_factory=dict)
    config: str = ""


class ChainManifest(BaseModel):
    model_config = ConfigDict(extra="ignore")

    chain_slug: str
    output_dir: str = "okf"
    generated_files: list[str] = Field(default_factory=list)
    managed_indexes: list[str] = Field(default_factory=list)
    file_snapshots: dict[str, str] = Field(default_factory=dict)
    source_fingerprints: SourceFingerprints = Field(default_factory=SourceFingerprints)
    last_run_at: str = ""
    last_content_snapshot: str = ""
    # Baseline for git context on later update runs ("what happened in the
    # OKF repo since the last content-changing run?"). Informational only —
    # excluded from equality so a plain commit never churns the manifest.
    okf_git_head: str | None = None


class Manifest(BaseModel):
    model_config = ConfigDict(extra="ignore")

    version: int = 2
    chains: dict[str, ChainManifest] = Field(default_factory=dict)

    @model_validator(mode="before")
    @classmethod
    def _migrate_v1(cls, data):
        """Accept legacy v1 manifests and wrap them as a single chain entry."""
        if not isinstance(data, dict):
            return data
        if "chains" in data:
            return data
        if "chain_id" not in data:
            return data
        chain_id = data.get("chain_id")
        if not str(chain_id or "").strip():
            raise ValueError("legacy manifest has empty `chain_id`; cannot migrate")
        entry_keys = set(ChainManifest.model_fields)
        entry = {key: data[key] for key in entry_keys if key in data}
        return {"version": 2, "chains": {str(chain_id): entry}}

    @property
    def generated_files(self) -> list[str]:
        """All files generated by any chain in this target repo."""
        return sorted(
            {rel for chain in self.chains.values() for rel in chain.generated_files}
        )

    @property
    def managed_indexes(self) -> list[str]:
        """All indexes managed by any chain in this target repo."""
        return sorted(
            {rel for chain in self.chains.values() for rel in chain.managed_indexes}
        )

    def matching_index_snapshot(self, rel: str, text: str) -> bool:
        """Return true when any chain entry recognizes the current index bytes."""
        current = compute_snapshot({rel: text})
        snapshots: list[str] = []
        for chain in self.chains.values():
            if rel not in set(chain.managed_indexes):
                continue
            recorded = chain.file_snapshots.get(rel)
            if recorded:
                snapshots.append(recorded)
        if not snapshots:
            # Backward-compatible ownership for old manifests without
            # per-file index snapshots.
            return True
        return current in set(snapshots)


def manifest_path(root: str | Path) -> Path:
    return Path(root) / MANIFEST_FILE


def manifest_lock_path(root: str | Path) -> Path:
    return manifest_path(root).with_name("manifest.lock")


@contextmanager
def manifest_lock(
    root: str | Path, *, timeout_seconds: float = 30.0, poll_seconds: float = 0.05
) -> Iterator[None]:
    """Serialize manifest commits across overlapping generate/update runs."""
    path = manifest_lock_path(root)
    path.parent.mkdir(parents=True, exist_ok=True)
    deadline = time.monotonic() + timeout_seconds
    fd: int | None = None
    while fd is None:
        try:
            fd = os.open(path, os.O_CREAT | os.O_EXCL | os.O_WRONLY)
            os.write(fd, f"{os.getpid()}\n".encode("ascii"))
        except FileExistsError as exc:
            if time.monotonic() >= deadline:
                raise ManifestLockError(
                    f"timed out waiting for manifest lock at {path}"
                ) from exc
            time.sleep(poll_seconds)
    try:
        yield
    finally:
        if fd is not None:
            os.close(fd)
        try:
            path.unlink()
        except FileNotFoundError:
            pass


def load_manifest(root: str | Path) -> Manifest | None:
    path = manifest_path(root)
    if not path.exists():
        return None
    data = yaml.safe_load(path.read_text(encoding="utf-8"))
    if not isinstance(data, dict):
        return None
    return Manifest.model_validate(data)


def save_manifest(root: str | Path, manifest: Manifest) -> Path:
    path = manifest_path(root)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(
        yaml.safe_dump(manifest.model_dump(), sort_keys=False, allow_unicode=True),
        encoding="utf-8",
    )
    return path


def compute_snapshot(contents: dict[str, str]) -> str:
    """Deterministic content snapshot over {rel_path: file_content}."""
    digest = hashlib.sha256()
    for rel in sorted(contents):
        digest.update(rel.encode("utf-8"))
        digest.update(b"\0")
        digest.update(contents[rel].encode("utf-8"))
        digest.update(b"\0")
    return f"sha256:{digest.hexdigest()}"


def compute_file_snapshots(contents: dict[str, str]) -> dict[str, str]:
    """Per-file content hashes for ownership drift checks."""
    return {rel: compute_snapshot({rel: text}) for rel, text in sorted(contents.items())}


def manifests_equal_ignoring_run_time(a: Manifest, b: Manifest) -> bool:
    def stable(manifest: Manifest) -> dict:
        data = manifest.model_dump()
        for chain in data.get("chains", {}).values():
            chain.pop("last_run_at", None)
            chain.pop("okf_git_head", None)
        return data

    return stable(a) == stable(b)


# --- Fingerprint diffing ---------------------------------------------------------


@dataclass
class SourceChanges:
    """Evidence sources whose fingerprints differ between two manifests."""

    raw_docs: list[str] = field(default_factory=list)
    repos: list[str] = field(default_factory=list)
    bigquery: list[str] = field(default_factory=list)
    reports: list[str] = field(default_factory=list)
    slack: list[str] = field(default_factory=list)
    config: bool = False

    def any(self) -> bool:
        return bool(
            self.raw_docs
            or self.repos
            or self.bigquery
            or self.reports
            or self.slack
            or self.config
        )

    def describe(self) -> list[str]:
        lines = []
        if self.config:
            lines.append("chain config changed")
        lines.extend(f"raw doc `{p}` changed" for p in self.raw_docs)
        lines.extend(f"repo `{r}` changed" for r in self.repos)
        lines.extend(f"bigquery table `{t}` changed" for t in self.bigquery)
        lines.extend(f"report `{r}` mapping changed" for r in self.reports)
        lines.extend(f"slack source `{s}` changed" for s in self.slack)
        return lines


def _changed_keys(old: dict, new: dict) -> list[str]:
    """Keys added, removed, or with a different value."""
    return sorted(k for k in set(old) | set(new) if old.get(k) != new.get(k))


def diff_fingerprints(old: SourceFingerprints, new: SourceFingerprints) -> SourceChanges:
    return SourceChanges(
        raw_docs=_changed_keys(old.raw_docs, new.raw_docs),
        repos=_changed_keys(
            {k: v.model_dump() for k, v in old.repos.items()},
            {k: v.model_dump() for k, v in new.repos.items()},
        ),
        bigquery=_changed_keys(old.bigquery, new.bigquery),
        reports=_changed_keys(old.reports, new.reports),
        slack=_changed_keys(old.slack, new.slack),
        config=old.config != new.config,
    )
